scheme: Gemini
menu:
  home: /|| fa fa-home
  tags:   /tags|| fa fa-tags
  archives: /archives|| fa fa-archive
search:
  path: ./public/search.xml
  field: post
  format: html
  limit: 10000
local_search:
  enable: true